apiVersion: v1
kind: Service
metadata:
  name: flood-prediction-service
spec:
  selector:
    app: flood-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
